version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: eficiencia_postgres
    restart: always
    environment:
      POSTGRES_USER: eficiencia_db
      POSTGRES_PASSWORD: ñStefaBren_bd
      POSTGRES_DB: eficiencia_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: